algoritmo "ALUNO_APROVADO"
var
   N1, N2: INTEIRO
   Media: real
inicio
      escreval ("ESCOLA MICHAEL DOUGLAS")
      escreva ("Primeira nota: ")
      leia (N1)
      Escreva ("Segunda nota: ")
      leia (N2)
      media <- (n1 + n2) / 2
      se (media<=7) entao
     escrevaL ("MÉDIA: ", media)
      
      fimse




            escrevaL ("MÉDIA: ", media,)




fimalgoritmo