algoritmo "RealParaDolar"
var
   C, Q: inteiro
   R, D: real

inicio
      C <-1
      Escreva ("Quantas vezes voce quer converter? ")
      Leia (Q)
           Enquanto (c<= Q) faca
           Escreval ("Escreva qual o valor em R$? ")
           Leia (R)
           D <- R / 2.20
           EscrevaL ("O valor convertido é US$", D:5:2)
           c <- c + 1
           
      FimEnquanto
fimalgoritmo